/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'id' : string,
  'country' : string,
  'flatNo' : string,
  'city' : string,
  'building' : string,
  'society' : string,
  'state' : string,
  'isDefault' : boolean,
  'pinCode' : string,
  'landmark' : string,
}
export interface AdminSession {
  'token' : string,
  'expiresAt' : bigint,
  'email' : string,
}
export interface AdminStats {
  'pendingPayments' : bigint,
  'totalOrders' : bigint,
  'pendingPickups' : bigint,
  'completedPickups' : bigint,
  'totalUsers' : bigint,
  'totalRevenue' : number,
}
export interface DiscountTier {
  'id' : string,
  'name' : string,
  'description' : string,
  'percentage' : number,
}
export interface LoyaltyStats {
  'totalPickups' : bigint,
  'userId' : Principal,
  'tier' : string,
  'discountPercent' : number,
  'ordersToNextTier' : bigint,
  'qualifyingOrderCount' : bigint,
}
export interface PaymentRecordShared {
  'id' : string,
  'status' : PaymentStatus,
  'finalAmount' : number,
  'userId' : Principal,
  'createdAt' : bigint,
  'upiTransactionId' : [] | [string],
  'discountPercent' : number,
  'updatedAt' : bigint,
  'pickupId' : string,
  'markedByAdmin' : boolean,
  'amount' : number,
}
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'refunded' : null } |
  { 'failed' : null };
export interface PickupRequest {
  'id' : string,
  'status' : PickupStatus,
  'isExpress' : boolean,
  'scheduledDate' : bigint,
  'userId' : Principal,
  'createdAt' : bigint,
  'discountPercent' : [] | [number],
  'isPaid' : boolean,
  'serviceIds' : Array<ServiceType>,
  'updatedAt' : bigint,
  'addressId' : string,
  'totalAmount' : [] | [number],
  'paymentId' : [] | [string],
  'timeSlot' : string,
}
export type PickupStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'pickupDone' : null } |
  { 'dropDone' : null };
export type PriceCategory = { 'men' : null } |
  { 'bulk' : null } |
  { 'kids' : null } |
  { 'shoes' : null } |
  { 'women' : null } |
  { 'household' : null };
export interface PriceItem {
  'id' : string,
  'ironingPrice' : [] | [number],
  'unit' : PriceUnit,
  'steamIroningPrice' : [] | [number],
  'dryCleaningPrice' : [] | [number],
  'updatedAt' : bigint,
  'itemName' : string,
  'category' : PriceCategory,
  'washFoldPrice' : [] | [number],
}
export type PriceUnit = { 'perPiece' : null } |
  { 'perSeat' : null } |
  { 'perMeter' : null } |
  { 'perKg' : null };
export interface RepeaterCategory {
  'totalPickups' : bigint,
  'userId' : Principal,
  'name' : string,
  'tier' : string,
  'discountPercent' : number,
  'phone' : string,
  'qualifyingOrderCount' : bigint,
}
export type Result = { 'ok' : boolean } |
  { 'err' : string };
export type Result_1 = { 'ok' : string } |
  { 'err' : string };
export type Result_2 = { 'ok' : UserProfile } |
  { 'err' : string };
export type Result_3 = { 'ok' : PickupRequest } |
  { 'err' : string };
export type Result_4 = { 'ok' : PaymentRecordShared } |
  { 'err' : string };
export type Result_5 = { 'ok' : AdminSession } |
  { 'err' : string };
export type ServiceType = { 'washFold' : null } |
  { 'shoeCleaning' : null } |
  { 'dryCleaning' : null } |
  { 'washSteamIron' : null } |
  { 'steamIron' : null };
export interface UserProfile {
  'id' : Principal,
  'otpCode' : [] | [string],
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'otpExpiry' : [] | [bigint],
  'addresses' : Array<Address>,
  'isVerified' : boolean,
  'passwordHash' : string,
  'phone' : string,
  'isPasswordConfigured' : boolean,
}
export interface _SERVICE {
  'addAddress' : ActorMethod<[Principal, Address], Result_1>,
  'addDiscountTier' : ActorMethod<[DiscountTier], Result_1>,
  'addPriceItem' : ActorMethod<[PriceItem], Result_1>,
  'adminLogin' : ActorMethod<[string, string], Result_5>,
  'assignCustomerDiscount' : ActorMethod<[Principal, string], Result>,
  'checkPasswordResetRequired' : ActorMethod<[], boolean>,
  'createPayment' : ActorMethod<[Principal, string, number], Result_1>,
  'createPickup' : ActorMethod<
    [Array<ServiceType>, bigint, string, string, boolean],
    Result_1
  >,
  'generateOTP' : ActorMethod<[string], Result_1>,
  'generateOTPForPasswordReset' : ActorMethod<[string], Result_1>,
  'getAddresses' : ActorMethod<[Principal], Array<Address>>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllPayments' : ActorMethod<[], Array<PaymentRecordShared>>,
  'getAllPickups' : ActorMethod<[], Array<PickupRequest>>,
  'getAllPrices' : ActorMethod<[], Array<PriceItem>>,
  'getCustomerDiscount' : ActorMethod<[Principal], [] | [DiscountTier]>,
  'getDiscountTiers' : ActorMethod<[], Array<DiscountTier>>,
  'getLoyaltyStats' : ActorMethod<[], Array<LoyaltyStats>>,
  'getMyLoyaltyStats' : ActorMethod<[], LoyaltyStats>,
  'getPayment' : ActorMethod<[string], Result_4>,
  'getPickup' : ActorMethod<[string], Result_3>,
  'getPricesByCategory' : ActorMethod<[PriceCategory], Array<PriceItem>>,
  'getRepeaterCustomers' : ActorMethod<[], Array<RepeaterCategory>>,
  'getUser' : ActorMethod<[Principal], Result_2>,
  'getUserPayments' : ActorMethod<[Principal], Array<PaymentRecordShared>>,
  'getUserPickups' : ActorMethod<[], Array<PickupRequest>>,
  'initAdminCredentials' : ActorMethod<[], undefined>,
  'initDefaultDiscountTiers' : ActorMethod<[], undefined>,
  'initDefaultPrices' : ActorMethod<[], undefined>,
  'loginUser' : ActorMethod<[string, string], Result_2>,
  'markPaymentPaid' : ActorMethod<[string, string, boolean], Result>,
  'markPaymentPending' : ActorMethod<[string], Result>,
  'markPickupPaid' : ActorMethod<[string, string], Result>,
  'registerUser' : ActorMethod<[string, string, string, string], Result_1>,
  'reschedulePickup' : ActorMethod<[string, bigint, string], Result>,
  'resetAdminPassword' : ActorMethod<[string, string], Result>,
  'resetPasswordWithOTP' : ActorMethod<[string, string, string], Result>,
  'setPickupAmount' : ActorMethod<[string, number, number], Result>,
  'setupPassword' : ActorMethod<[string, string, string], Result>,
  'updateAddress' : ActorMethod<[Principal, string, Address], Result>,
  'updateDiscountTier' : ActorMethod<[string, number], Result>,
  'updatePickupStatus' : ActorMethod<[string, PickupStatus], Result>,
  'updatePrice' : ActorMethod<
    [string, [] | [number], [] | [number], [] | [number], [] | [number]],
    Result
  >,
  'validateAdminToken' : ActorMethod<[string], Result>,
  'verifyOTP' : ActorMethod<[string, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];