/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Address = IDL.Record({
  'id' : IDL.Text,
  'country' : IDL.Text,
  'flatNo' : IDL.Text,
  'city' : IDL.Text,
  'building' : IDL.Text,
  'society' : IDL.Text,
  'state' : IDL.Text,
  'isDefault' : IDL.Bool,
  'pinCode' : IDL.Text,
  'landmark' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const DiscountTier = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'percentage' : IDL.Float64,
});
export const PriceUnit = IDL.Variant({
  'perPiece' : IDL.Null,
  'perSeat' : IDL.Null,
  'perMeter' : IDL.Null,
  'perKg' : IDL.Null,
});
export const PriceCategory = IDL.Variant({
  'men' : IDL.Null,
  'bulk' : IDL.Null,
  'kids' : IDL.Null,
  'shoes' : IDL.Null,
  'women' : IDL.Null,
  'household' : IDL.Null,
});
export const PriceItem = IDL.Record({
  'id' : IDL.Text,
  'ironingPrice' : IDL.Opt(IDL.Float64),
  'unit' : PriceUnit,
  'steamIroningPrice' : IDL.Opt(IDL.Float64),
  'dryCleaningPrice' : IDL.Opt(IDL.Float64),
  'updatedAt' : IDL.Int,
  'itemName' : IDL.Text,
  'category' : PriceCategory,
  'washFoldPrice' : IDL.Opt(IDL.Float64),
});
export const AdminSession = IDL.Record({
  'token' : IDL.Text,
  'expiresAt' : IDL.Int,
  'email' : IDL.Text,
});
export const Result_5 = IDL.Variant({ 'ok' : AdminSession, 'err' : IDL.Text });
export const Result = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
export const ServiceType = IDL.Variant({
  'washFold' : IDL.Null,
  'shoeCleaning' : IDL.Null,
  'dryCleaning' : IDL.Null,
  'washSteamIron' : IDL.Null,
  'steamIron' : IDL.Null,
});
export const AdminStats = IDL.Record({
  'pendingPayments' : IDL.Int,
  'totalOrders' : IDL.Int,
  'pendingPickups' : IDL.Int,
  'completedPickups' : IDL.Int,
  'totalUsers' : IDL.Int,
  'totalRevenue' : IDL.Float64,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'refunded' : IDL.Null,
  'failed' : IDL.Null,
});
export const PaymentRecordShared = IDL.Record({
  'id' : IDL.Text,
  'status' : PaymentStatus,
  'finalAmount' : IDL.Float64,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'upiTransactionId' : IDL.Opt(IDL.Text),
  'discountPercent' : IDL.Float64,
  'updatedAt' : IDL.Int,
  'pickupId' : IDL.Text,
  'markedByAdmin' : IDL.Bool,
  'amount' : IDL.Float64,
});
export const PickupStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'pickupDone' : IDL.Null,
  'dropDone' : IDL.Null,
});
export const PickupRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : PickupStatus,
  'isExpress' : IDL.Bool,
  'scheduledDate' : IDL.Int,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'discountPercent' : IDL.Opt(IDL.Float64),
  'isPaid' : IDL.Bool,
  'serviceIds' : IDL.Vec(ServiceType),
  'updatedAt' : IDL.Int,
  'addressId' : IDL.Text,
  'totalAmount' : IDL.Opt(IDL.Float64),
  'paymentId' : IDL.Opt(IDL.Text),
  'timeSlot' : IDL.Text,
});
export const LoyaltyStats = IDL.Record({
  'totalPickups' : IDL.Int,
  'userId' : IDL.Principal,
  'tier' : IDL.Text,
  'discountPercent' : IDL.Float64,
  'ordersToNextTier' : IDL.Int,
  'qualifyingOrderCount' : IDL.Int,
});
export const Result_4 = IDL.Variant({
  'ok' : PaymentRecordShared,
  'err' : IDL.Text,
});
export const Result_3 = IDL.Variant({ 'ok' : PickupRequest, 'err' : IDL.Text });
export const RepeaterCategory = IDL.Record({
  'totalPickups' : IDL.Int,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'tier' : IDL.Text,
  'discountPercent' : IDL.Float64,
  'phone' : IDL.Text,
  'qualifyingOrderCount' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'otpCode' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'otpExpiry' : IDL.Opt(IDL.Int),
  'addresses' : IDL.Vec(Address),
  'isVerified' : IDL.Bool,
  'passwordHash' : IDL.Text,
  'phone' : IDL.Text,
  'isPasswordConfigured' : IDL.Bool,
});
export const Result_2 = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'addAddress' : IDL.Func([IDL.Principal, Address], [Result_1], []),
  'addDiscountTier' : IDL.Func([DiscountTier], [Result_1], []),
  'addPriceItem' : IDL.Func([PriceItem], [Result_1], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [Result_5], []),
  'assignCustomerDiscount' : IDL.Func([IDL.Principal, IDL.Text], [Result], []),
  'checkPasswordResetRequired' : IDL.Func([], [IDL.Bool], []),
  'createPayment' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Float64],
      [Result_1],
      [],
    ),
  'createPickup' : IDL.Func(
      [IDL.Vec(ServiceType), IDL.Int, IDL.Text, IDL.Text, IDL.Bool],
      [Result_1],
      [],
    ),
  'generateOTP' : IDL.Func([IDL.Text], [Result_1], []),
  'generateOTPForPasswordReset' : IDL.Func([IDL.Text], [Result_1], []),
  'getAddresses' : IDL.Func([IDL.Principal], [IDL.Vec(Address)], ['query']),
  'getAdminStats' : IDL.Func([], [AdminStats], []),
  'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentRecordShared)], []),
  'getAllPickups' : IDL.Func([], [IDL.Vec(PickupRequest)], ['query']),
  'getAllPrices' : IDL.Func([], [IDL.Vec(PriceItem)], ['query']),
  'getCustomerDiscount' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(DiscountTier)],
      ['query'],
    ),
  'getDiscountTiers' : IDL.Func([], [IDL.Vec(DiscountTier)], ['query']),
  'getLoyaltyStats' : IDL.Func([], [IDL.Vec(LoyaltyStats)], ['query']),
  'getMyLoyaltyStats' : IDL.Func([], [LoyaltyStats], ['query']),
  'getPayment' : IDL.Func([IDL.Text], [Result_4], []),
  'getPickup' : IDL.Func([IDL.Text], [Result_3], ['query']),
  'getPricesByCategory' : IDL.Func(
      [PriceCategory],
      [IDL.Vec(PriceItem)],
      ['query'],
    ),
  'getRepeaterCustomers' : IDL.Func([], [IDL.Vec(RepeaterCategory)], []),
  'getUser' : IDL.Func([IDL.Principal], [Result_2], ['query']),
  'getUserPayments' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PaymentRecordShared)],
      [],
    ),
  'getUserPickups' : IDL.Func([], [IDL.Vec(PickupRequest)], ['query']),
  'initAdminCredentials' : IDL.Func([], [], []),
  'initDefaultDiscountTiers' : IDL.Func([], [], []),
  'initDefaultPrices' : IDL.Func([], [], []),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
  'markPaymentPaid' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [Result], []),
  'markPaymentPending' : IDL.Func([IDL.Text], [Result], []),
  'markPickupPaid' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_1],
      [],
    ),
  'reschedulePickup' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [Result], []),
  'resetAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'resetPasswordWithOTP' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'setPickupAmount' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64],
      [Result],
      [],
    ),
  'setupPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  'updateAddress' : IDL.Func([IDL.Principal, IDL.Text, Address], [Result], []),
  'updateDiscountTier' : IDL.Func([IDL.Text, IDL.Float64], [Result], []),
  'updatePickupStatus' : IDL.Func([IDL.Text, PickupStatus], [Result], []),
  'updatePrice' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
      ],
      [Result],
      [],
    ),
  'validateAdminToken' : IDL.Func([IDL.Text], [Result], []),
  'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Address = IDL.Record({
    'id' : IDL.Text,
    'country' : IDL.Text,
    'flatNo' : IDL.Text,
    'city' : IDL.Text,
    'building' : IDL.Text,
    'society' : IDL.Text,
    'state' : IDL.Text,
    'isDefault' : IDL.Bool,
    'pinCode' : IDL.Text,
    'landmark' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const DiscountTier = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'percentage' : IDL.Float64,
  });
  const PriceUnit = IDL.Variant({
    'perPiece' : IDL.Null,
    'perSeat' : IDL.Null,
    'perMeter' : IDL.Null,
    'perKg' : IDL.Null,
  });
  const PriceCategory = IDL.Variant({
    'men' : IDL.Null,
    'bulk' : IDL.Null,
    'kids' : IDL.Null,
    'shoes' : IDL.Null,
    'women' : IDL.Null,
    'household' : IDL.Null,
  });
  const PriceItem = IDL.Record({
    'id' : IDL.Text,
    'ironingPrice' : IDL.Opt(IDL.Float64),
    'unit' : PriceUnit,
    'steamIroningPrice' : IDL.Opt(IDL.Float64),
    'dryCleaningPrice' : IDL.Opt(IDL.Float64),
    'updatedAt' : IDL.Int,
    'itemName' : IDL.Text,
    'category' : PriceCategory,
    'washFoldPrice' : IDL.Opt(IDL.Float64),
  });
  const AdminSession = IDL.Record({
    'token' : IDL.Text,
    'expiresAt' : IDL.Int,
    'email' : IDL.Text,
  });
  const Result_5 = IDL.Variant({ 'ok' : AdminSession, 'err' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const ServiceType = IDL.Variant({
    'washFold' : IDL.Null,
    'shoeCleaning' : IDL.Null,
    'dryCleaning' : IDL.Null,
    'washSteamIron' : IDL.Null,
    'steamIron' : IDL.Null,
  });
  const AdminStats = IDL.Record({
    'pendingPayments' : IDL.Int,
    'totalOrders' : IDL.Int,
    'pendingPickups' : IDL.Int,
    'completedPickups' : IDL.Int,
    'totalUsers' : IDL.Int,
    'totalRevenue' : IDL.Float64,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'refunded' : IDL.Null,
    'failed' : IDL.Null,
  });
  const PaymentRecordShared = IDL.Record({
    'id' : IDL.Text,
    'status' : PaymentStatus,
    'finalAmount' : IDL.Float64,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'upiTransactionId' : IDL.Opt(IDL.Text),
    'discountPercent' : IDL.Float64,
    'updatedAt' : IDL.Int,
    'pickupId' : IDL.Text,
    'markedByAdmin' : IDL.Bool,
    'amount' : IDL.Float64,
  });
  const PickupStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'pickupDone' : IDL.Null,
    'dropDone' : IDL.Null,
  });
  const PickupRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : PickupStatus,
    'isExpress' : IDL.Bool,
    'scheduledDate' : IDL.Int,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'discountPercent' : IDL.Opt(IDL.Float64),
    'isPaid' : IDL.Bool,
    'serviceIds' : IDL.Vec(ServiceType),
    'updatedAt' : IDL.Int,
    'addressId' : IDL.Text,
    'totalAmount' : IDL.Opt(IDL.Float64),
    'paymentId' : IDL.Opt(IDL.Text),
    'timeSlot' : IDL.Text,
  });
  const LoyaltyStats = IDL.Record({
    'totalPickups' : IDL.Int,
    'userId' : IDL.Principal,
    'tier' : IDL.Text,
    'discountPercent' : IDL.Float64,
    'ordersToNextTier' : IDL.Int,
    'qualifyingOrderCount' : IDL.Int,
  });
  const Result_4 = IDL.Variant({
    'ok' : PaymentRecordShared,
    'err' : IDL.Text,
  });
  const Result_3 = IDL.Variant({ 'ok' : PickupRequest, 'err' : IDL.Text });
  const RepeaterCategory = IDL.Record({
    'totalPickups' : IDL.Int,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'tier' : IDL.Text,
    'discountPercent' : IDL.Float64,
    'phone' : IDL.Text,
    'qualifyingOrderCount' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'otpCode' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'otpExpiry' : IDL.Opt(IDL.Int),
    'addresses' : IDL.Vec(Address),
    'isVerified' : IDL.Bool,
    'passwordHash' : IDL.Text,
    'phone' : IDL.Text,
    'isPasswordConfigured' : IDL.Bool,
  });
  const Result_2 = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
  
  return IDL.Service({
    'addAddress' : IDL.Func([IDL.Principal, Address], [Result_1], []),
    'addDiscountTier' : IDL.Func([DiscountTier], [Result_1], []),
    'addPriceItem' : IDL.Func([PriceItem], [Result_1], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [Result_5], []),
    'assignCustomerDiscount' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [Result],
        [],
      ),
    'checkPasswordResetRequired' : IDL.Func([], [IDL.Bool], []),
    'createPayment' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Float64],
        [Result_1],
        [],
      ),
    'createPickup' : IDL.Func(
        [IDL.Vec(ServiceType), IDL.Int, IDL.Text, IDL.Text, IDL.Bool],
        [Result_1],
        [],
      ),
    'generateOTP' : IDL.Func([IDL.Text], [Result_1], []),
    'generateOTPForPasswordReset' : IDL.Func([IDL.Text], [Result_1], []),
    'getAddresses' : IDL.Func([IDL.Principal], [IDL.Vec(Address)], ['query']),
    'getAdminStats' : IDL.Func([], [AdminStats], []),
    'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentRecordShared)], []),
    'getAllPickups' : IDL.Func([], [IDL.Vec(PickupRequest)], ['query']),
    'getAllPrices' : IDL.Func([], [IDL.Vec(PriceItem)], ['query']),
    'getCustomerDiscount' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(DiscountTier)],
        ['query'],
      ),
    'getDiscountTiers' : IDL.Func([], [IDL.Vec(DiscountTier)], ['query']),
    'getLoyaltyStats' : IDL.Func([], [IDL.Vec(LoyaltyStats)], ['query']),
    'getMyLoyaltyStats' : IDL.Func([], [LoyaltyStats], ['query']),
    'getPayment' : IDL.Func([IDL.Text], [Result_4], []),
    'getPickup' : IDL.Func([IDL.Text], [Result_3], ['query']),
    'getPricesByCategory' : IDL.Func(
        [PriceCategory],
        [IDL.Vec(PriceItem)],
        ['query'],
      ),
    'getRepeaterCustomers' : IDL.Func([], [IDL.Vec(RepeaterCategory)], []),
    'getUser' : IDL.Func([IDL.Principal], [Result_2], ['query']),
    'getUserPayments' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PaymentRecordShared)],
        [],
      ),
    'getUserPickups' : IDL.Func([], [IDL.Vec(PickupRequest)], ['query']),
    'initAdminCredentials' : IDL.Func([], [], []),
    'initDefaultDiscountTiers' : IDL.Func([], [], []),
    'initDefaultPrices' : IDL.Func([], [], []),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
    'markPaymentPaid' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [Result], []),
    'markPaymentPending' : IDL.Func([IDL.Text], [Result], []),
    'markPickupPaid' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'reschedulePickup' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [Result], []),
    'resetAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'resetPasswordWithOTP' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'setPickupAmount' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64],
        [Result],
        [],
      ),
    'setupPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
    'updateAddress' : IDL.Func(
        [IDL.Principal, IDL.Text, Address],
        [Result],
        [],
      ),
    'updateDiscountTier' : IDL.Func([IDL.Text, IDL.Float64], [Result], []),
    'updatePickupStatus' : IDL.Func([IDL.Text, PickupStatus], [Result], []),
    'updatePrice' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
        ],
        [Result],
        [],
      ),
    'validateAdminToken' : IDL.Func([IDL.Text], [Result], []),
    'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };