/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Result_2 = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
};
export interface PriceItem {
    id: string;
    ironingPrice?: number;
    unit: PriceUnit;
    steamIroningPrice?: number;
    dryCleaningPrice?: number;
    updatedAt: bigint;
    itemName: string;
    category: PriceCategory;
    washFoldPrice?: number;
}
export interface PaymentRecordShared {
    id: string;
    status: PaymentStatus;
    finalAmount: number;
    userId: Principal;
    createdAt: bigint;
    upiTransactionId?: string;
    discountPercent: number;
    updatedAt: bigint;
    pickupId: string;
    markedByAdmin: boolean;
    amount: number;
}
export interface DiscountTier {
    id: string;
    name: string;
    description: string;
    percentage: number;
}
export type Result_5 = {
    __kind__: "ok";
    ok: AdminSession;
} | {
    __kind__: "err";
    err: string;
};
export interface RepeaterCategory {
    totalPickups: bigint;
    userId: Principal;
    name: string;
    tier: string;
    discountPercent: number;
    phone: string;
    qualifyingOrderCount: bigint;
}
export type Result_1 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface PickupRequest {
    id: string;
    status: PickupStatus;
    isExpress: boolean;
    scheduledDate: bigint;
    userId: Principal;
    createdAt: bigint;
    discountPercent?: number;
    isPaid: boolean;
    serviceIds: Array<ServiceType>;
    updatedAt: bigint;
    addressId: string;
    totalAmount?: number;
    paymentId?: string;
    timeSlot: string;
}
export type Result_4 = {
    __kind__: "ok";
    ok: PaymentRecordShared;
} | {
    __kind__: "err";
    err: string;
};
export interface AdminSession {
    token: string;
    expiresAt: bigint;
    email: string;
}
export type Result = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: PickupRequest;
} | {
    __kind__: "err";
    err: string;
};
export interface AdminStats {
    pendingPayments: bigint;
    totalOrders: bigint;
    pendingPickups: bigint;
    completedPickups: bigint;
    totalUsers: bigint;
    totalRevenue: number;
}
export interface LoyaltyStats {
    totalPickups: bigint;
    userId: Principal;
    tier: string;
    discountPercent: number;
    ordersToNextTier: bigint;
    qualifyingOrderCount: bigint;
}
export interface UserProfile {
    id: Principal;
    otpCode?: string;
    name: string;
    createdAt: bigint;
    email: string;
    otpExpiry?: bigint;
    addresses: Array<Address>;
    isVerified: boolean;
    passwordHash: string;
    phone: string;
    isPasswordConfigured: boolean;
}
export interface Address {
    id: string;
    country: string;
    flatNo: string;
    city: string;
    building: string;
    society: string;
    state: string;
    isDefault: boolean;
    pinCode: string;
    landmark: string;
}
export enum PaymentStatus {
    pending = "pending",
    paid = "paid",
    refunded = "refunded",
    failed = "failed"
}
export enum PickupStatus {
    cancelled = "cancelled",
    pending = "pending",
    pickupDone = "pickupDone",
    dropDone = "dropDone"
}
export enum PriceCategory {
    men = "men",
    bulk = "bulk",
    kids = "kids",
    shoes = "shoes",
    women = "women",
    household = "household"
}
export enum PriceUnit {
    perPiece = "perPiece",
    perSeat = "perSeat",
    perMeter = "perMeter",
    perKg = "perKg"
}
export enum ServiceType {
    washFold = "washFold",
    shoeCleaning = "shoeCleaning",
    dryCleaning = "dryCleaning",
    washSteamIron = "washSteamIron",
    steamIron = "steamIron"
}
export interface backendInterface {
    addAddress(userId: Principal, address: Address): Promise<Result_1>;
    addDiscountTier(tier: DiscountTier): Promise<Result_1>;
    addPriceItem(item: PriceItem): Promise<Result_1>;
    adminLogin(email: string, password: string): Promise<Result_5>;
    assignCustomerDiscount(userId: Principal, tierId: string): Promise<Result>;
    checkPasswordResetRequired(): Promise<boolean>;
    createPayment(userId: Principal, pickupId: string, amount: number): Promise<Result_1>;
    createPickup(serviceIds: Array<ServiceType>, scheduledDate: bigint, timeSlot: string, addressId: string, isExpress: boolean): Promise<Result_1>;
    generateOTP(phone: string): Promise<Result_1>;
    generateOTPForPasswordReset(phone: string): Promise<Result_1>;
    getAddresses(userId: Principal): Promise<Array<Address>>;
    getAdminStats(): Promise<AdminStats>;
    getAllPayments(): Promise<Array<PaymentRecordShared>>;
    getAllPickups(): Promise<Array<PickupRequest>>;
    getAllPrices(): Promise<Array<PriceItem>>;
    getCustomerDiscount(userId: Principal): Promise<DiscountTier | null>;
    getDiscountTiers(): Promise<Array<DiscountTier>>;
    getLoyaltyStats(): Promise<Array<LoyaltyStats>>;
    getMyLoyaltyStats(): Promise<LoyaltyStats>;
    getPayment(paymentId: string): Promise<Result_4>;
    getPickup(pickupId: string): Promise<Result_3>;
    getPricesByCategory(category: PriceCategory): Promise<Array<PriceItem>>;
    getRepeaterCustomers(): Promise<Array<RepeaterCategory>>;
    getUser(userId: Principal): Promise<Result_2>;
    getUserPayments(userId: Principal): Promise<Array<PaymentRecordShared>>;
    getUserPickups(): Promise<Array<PickupRequest>>;
    initAdminCredentials(): Promise<void>;
    initDefaultDiscountTiers(): Promise<void>;
    initDefaultPrices(): Promise<void>;
    loginUser(phone: string, password: string): Promise<Result_2>;
    markPaymentPaid(paymentId: string, upiTransactionId: string, byAdmin: boolean): Promise<Result>;
    markPaymentPending(paymentId: string): Promise<Result>;
    markPickupPaid(pickupId: string, paymentId: string): Promise<Result>;
    registerUser(phone: string, name: string, email: string, password: string): Promise<Result_1>;
    reschedulePickup(pickupId: string, newDate: bigint, newTimeSlot: string): Promise<Result>;
    resetAdminPassword(currentPassword: string, newPassword: string): Promise<Result>;
    resetPasswordWithOTP(phone: string, otp: string, newPassword: string): Promise<Result>;
    setPickupAmount(pickupId: string, amount: number, discountPercent: number): Promise<Result>;
    setupPassword(phone: string, otp: string, newPassword: string): Promise<Result>;
    updateAddress(userId: Principal, addressId: string, address: Address): Promise<Result>;
    updateDiscountTier(tierId: string, percentage: number): Promise<Result>;
    updatePickupStatus(pickupId: string, status: PickupStatus): Promise<Result>;
    updatePrice(itemId: string, ironingPrice: number | null, steamIroningPrice: number | null, dryCleaningPrice: number | null, washFoldPrice: number | null): Promise<Result>;
    validateAdminToken(token: string): Promise<Result>;
    verifyOTP(phone: string, otp: string): Promise<Result>;
}
import type { Address as _Address, AdminSession as _AdminSession, DiscountTier as _DiscountTier, PaymentRecordShared as _PaymentRecordShared, PaymentStatus as _PaymentStatus, PickupRequest as _PickupRequest, PickupStatus as _PickupStatus, PriceCategory as _PriceCategory, PriceItem as _PriceItem, PriceUnit as _PriceUnit, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, ServiceType as _ServiceType, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAddress(arg0: Principal, arg1: Address): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addAddress(arg0, arg1);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAddress(arg0, arg1);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addDiscountTier(arg0: DiscountTier): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addDiscountTier(arg0);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDiscountTier(arg0);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPriceItem(arg0: PriceItem): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addPriceItem(to_candid_PriceItem_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPriceItem(to_candid_PriceItem_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return from_candid_Result_5_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return from_candid_Result_5_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCustomerDiscount(arg0: Principal, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCustomerDiscount(arg0, arg1);
                return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCustomerDiscount(arg0, arg1);
            return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkPasswordResetRequired(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkPasswordResetRequired();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkPasswordResetRequired();
            return result;
        }
    }
    async createPayment(arg0: Principal, arg1: string, arg2: number): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayment(arg0, arg1, arg2);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayment(arg0, arg1, arg2);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPickup(arg0: Array<ServiceType>, arg1: bigint, arg2: string, arg3: string, arg4: boolean): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createPickup(to_candid_vec_n13(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPickup(to_candid_vec_n13(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateOTP(arg0: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.generateOTP(arg0);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateOTP(arg0);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateOTPForPasswordReset(arg0: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.generateOTPForPasswordReset(arg0);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateOTPForPasswordReset(arg0);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAddresses(arg0: Principal): Promise<Array<Address>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAddresses(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAddresses(arg0);
            return result;
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAllPayments(): Promise<Array<PaymentRecordShared>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPickups(): Promise<Array<PickupRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPickups();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPickups();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPrices(): Promise<Array<PriceItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPrices();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPrices();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerDiscount(arg0: Principal): Promise<DiscountTier | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerDiscount(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerDiscount(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDiscountTiers(): Promise<Array<DiscountTier>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiscountTiers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiscountTiers();
            return result;
        }
    }
    async getLoyaltyStats(): Promise<Array<LoyaltyStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoyaltyStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoyaltyStats();
            return result;
        }
    }
    async getMyLoyaltyStats(): Promise<LoyaltyStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLoyaltyStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLoyaltyStats();
            return result;
        }
    }
    async getPayment(arg0: string): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return from_candid_Result_4_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return from_candid_Result_4_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPickup(arg0: string): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.getPickup(arg0);
                return from_candid_Result_3_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPickup(arg0);
            return from_candid_Result_3_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPricesByCategory(arg0: PriceCategory): Promise<Array<PriceItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPricesByCategory(to_candid_PriceCategory_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPricesByCategory(to_candid_PriceCategory_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRepeaterCustomers(): Promise<Array<RepeaterCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRepeaterCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRepeaterCustomers();
            return result;
        }
    }
    async getUser(arg0: Principal): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_Result_2_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_Result_2_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPayments(arg0: Principal): Promise<Array<PaymentRecordShared>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPayments(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPayments(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPickups(): Promise<Array<PickupRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPickups();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPickups();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async initAdminCredentials(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initAdminCredentials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initAdminCredentials();
            return result;
        }
    }
    async initDefaultDiscountTiers(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initDefaultDiscountTiers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initDefaultDiscountTiers();
            return result;
        }
    }
    async initDefaultPrices(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initDefaultPrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initDefaultPrices();
            return result;
        }
    }
    async loginUser(arg0: string, arg1: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0, arg1);
                return from_candid_Result_2_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0, arg1);
            return from_candid_Result_2_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async markPaymentPaid(arg0: string, arg1: string, arg2: boolean): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.markPaymentPaid(arg0, arg1, arg2);
                return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPaymentPaid(arg0, arg1, arg2);
            return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async markPaymentPending(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.markPaymentPending(arg0);
                return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPaymentPending(arg0);
            return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async markPickupPaid(arg0: string, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.markPickupPaid(arg0, arg1);
                return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPickupPaid(arg0, arg1);
            return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, arg3);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, arg3);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async reschedulePickup(arg0: string, arg1: bigint, arg2: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.reschedulePickup(arg0, arg1, arg2);
                return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reschedulePickup(arg0, arg1, arg2);
            return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetAdminPassword(arg0: string, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAdminPassword(arg0, arg1);
                return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAdminPassword(arg0, arg1);
            return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetPasswordWithOTP(arg0: string, arg1: string, arg2: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPasswordWithOTP(arg0, arg1, arg2);
                return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPasswordWithOTP(arg0, arg1, arg2);
            return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async setPickupAmount(arg0: string, arg1: number, arg2: number): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.setPickupAmount(arg0, arg1, arg2);
                return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPickupAmount(arg0, arg1, arg2);
            return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async setupPassword(arg0: string, arg1: string, arg2: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.setupPassword(arg0, arg1, arg2);
                return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setupPassword(arg0, arg1, arg2);
            return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAddress(arg0: Principal, arg1: string, arg2: Address): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAddress(arg0, arg1, arg2);
                return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAddress(arg0, arg1, arg2);
            return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDiscountTier(arg0: string, arg1: number): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDiscountTier(arg0, arg1);
                return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDiscountTier(arg0, arg1);
            return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePickupStatus(arg0: string, arg1: PickupStatus): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePickupStatus(arg0, to_candid_PickupStatus_n48(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePickupStatus(arg0, to_candid_PickupStatus_n48(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePrice(arg0: string, arg1: number | null, arg2: number | null, arg3: number | null, arg4: number | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrice(arg0, to_candid_opt_n50(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrice(arg0, to_candid_opt_n50(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateAdminToken(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.validateAdminToken(arg0);
                return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateAdminToken(arg0);
            return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyOTP(arg0: string, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyOTP(arg0, arg1);
                return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyOTP(arg0, arg1);
            return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_PaymentRecordShared_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRecordShared): PaymentRecordShared {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PickupRequest_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PickupRequest): PickupRequest {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PickupStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PickupStatus): PickupStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_PriceCategory_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceCategory): PriceCategory {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_PriceItem_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceItem): PriceItem {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_PriceUnit_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceUnit): PriceUnit {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DiscountTier]): DiscountTier | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _PaymentStatus;
    finalAmount: number;
    userId: Principal;
    createdAt: bigint;
    upiTransactionId: [] | [string];
    discountPercent: number;
    updatedAt: bigint;
    pickupId: string;
    markedByAdmin: boolean;
    amount: number;
}): {
    id: string;
    status: PaymentStatus;
    finalAmount: number;
    userId: Principal;
    createdAt: bigint;
    upiTransactionId?: string;
    discountPercent: number;
    updatedAt: bigint;
    pickupId: string;
    markedByAdmin: boolean;
    amount: number;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n19(_uploadFile, _downloadFile, value.status),
        finalAmount: value.finalAmount,
        userId: value.userId,
        createdAt: value.createdAt,
        upiTransactionId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.upiTransactionId)),
        discountPercent: value.discountPercent,
        updatedAt: value.updatedAt,
        pickupId: value.pickupId,
        markedByAdmin: value.markedByAdmin,
        amount: value.amount
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _PickupStatus;
    isExpress: boolean;
    scheduledDate: bigint;
    userId: Principal;
    createdAt: bigint;
    discountPercent: [] | [number];
    isPaid: boolean;
    serviceIds: Array<_ServiceType>;
    updatedAt: bigint;
    addressId: string;
    totalAmount: [] | [number];
    paymentId: [] | [string];
    timeSlot: string;
}): {
    id: string;
    status: PickupStatus;
    isExpress: boolean;
    scheduledDate: bigint;
    userId: Principal;
    createdAt: bigint;
    discountPercent?: number;
    isPaid: boolean;
    serviceIds: Array<ServiceType>;
    updatedAt: bigint;
    addressId: string;
    totalAmount?: number;
    paymentId?: string;
    timeSlot: string;
} {
    return {
        id: value.id,
        status: from_candid_PickupStatus_n25(_uploadFile, _downloadFile, value.status),
        isExpress: value.isExpress,
        scheduledDate: value.scheduledDate,
        userId: value.userId,
        createdAt: value.createdAt,
        discountPercent: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.discountPercent)),
        isPaid: value.isPaid,
        serviceIds: from_candid_vec_n28(_uploadFile, _downloadFile, value.serviceIds),
        updatedAt: value.updatedAt,
        addressId: value.addressId,
        totalAmount: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.totalAmount)),
        paymentId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.paymentId)),
        timeSlot: value.timeSlot
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    ironingPrice: [] | [number];
    unit: _PriceUnit;
    steamIroningPrice: [] | [number];
    dryCleaningPrice: [] | [number];
    updatedAt: bigint;
    itemName: string;
    category: _PriceCategory;
    washFoldPrice: [] | [number];
}): {
    id: string;
    ironingPrice?: number;
    unit: PriceUnit;
    steamIroningPrice?: number;
    dryCleaningPrice?: number;
    updatedAt: bigint;
    itemName: string;
    category: PriceCategory;
    washFoldPrice?: number;
} {
    return {
        id: value.id,
        ironingPrice: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.ironingPrice)),
        unit: from_candid_PriceUnit_n34(_uploadFile, _downloadFile, value.unit),
        steamIroningPrice: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.steamIroningPrice)),
        dryCleaningPrice: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.dryCleaningPrice)),
        updatedAt: value.updatedAt,
        itemName: value.itemName,
        category: from_candid_PriceCategory_n36(_uploadFile, _downloadFile, value.category),
        washFoldPrice: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.washFoldPrice))
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    otpCode: [] | [string];
    name: string;
    createdAt: bigint;
    email: string;
    otpExpiry: [] | [bigint];
    addresses: Array<_Address>;
    isVerified: boolean;
    passwordHash: string;
    phone: string;
    isPasswordConfigured: boolean;
}): {
    id: Principal;
    otpCode?: string;
    name: string;
    createdAt: bigint;
    email: string;
    otpExpiry?: bigint;
    addresses: Array<Address>;
    isVerified: boolean;
    passwordHash: string;
    phone: string;
    isPasswordConfigured: boolean;
} {
    return {
        id: value.id,
        otpCode: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.otpCode)),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        otpExpiry: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.otpExpiry)),
        addresses: value.addresses,
        isVerified: value.isVerified,
        passwordHash: value.passwordHash,
        phone: value.phone,
        isPasswordConfigured: value.isPasswordConfigured
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AdminSession;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AdminSession;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    refunded: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : "refunded" in value ? PaymentStatus.refunded : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    pickupDone: null;
} | {
    dropDone: null;
}): PickupStatus {
    return "cancelled" in value ? PickupStatus.cancelled : "pending" in value ? PickupStatus.pending : "pickupDone" in value ? PickupStatus.pickupDone : "dropDone" in value ? PickupStatus.dropDone : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    washFold: null;
} | {
    shoeCleaning: null;
} | {
    dryCleaning: null;
} | {
    washSteamIron: null;
} | {
    steamIron: null;
}): ServiceType {
    return "washFold" in value ? ServiceType.washFold : "shoeCleaning" in value ? ServiceType.shoeCleaning : "dryCleaning" in value ? ServiceType.dryCleaning : "washSteamIron" in value ? ServiceType.washSteamIron : "steamIron" in value ? ServiceType.steamIron : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    perPiece: null;
} | {
    perSeat: null;
} | {
    perMeter: null;
} | {
    perKg: null;
}): PriceUnit {
    return "perPiece" in value ? PriceUnit.perPiece : "perSeat" in value ? PriceUnit.perSeat : "perMeter" in value ? PriceUnit.perMeter : "perKg" in value ? PriceUnit.perKg : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    men: null;
} | {
    bulk: null;
} | {
    kids: null;
} | {
    shoes: null;
} | {
    women: null;
} | {
    household: null;
}): PriceCategory {
    return "men" in value ? PriceCategory.men : "bulk" in value ? PriceCategory.bulk : "kids" in value ? PriceCategory.kids : "shoes" in value ? PriceCategory.shoes : "women" in value ? PriceCategory.women : "household" in value ? PriceCategory.household : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PaymentRecordShared;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PaymentRecordShared;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PaymentRecordShared_n17(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PickupRequest;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PickupRequest;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PickupRequest_n23(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n45(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentRecordShared>): Array<PaymentRecordShared> {
    return value.map((x)=>from_candid_PaymentRecordShared_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PickupRequest>): Array<PickupRequest> {
    return value.map((x)=>from_candid_PickupRequest_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceType>): Array<ServiceType> {
    return value.map((x)=>from_candid_ServiceType_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PriceItem>): Array<PriceItem> {
    return value.map((x)=>from_candid_PriceItem_n32(_uploadFile, _downloadFile, x));
}
function to_candid_PickupStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PickupStatus): _PickupStatus {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_PriceCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceCategory): _PriceCategory {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_PriceItem_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceItem): _PriceItem {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_PriceUnit_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceUnit): _PriceUnit {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    ironingPrice?: number;
    unit: PriceUnit;
    steamIroningPrice?: number;
    dryCleaningPrice?: number;
    updatedAt: bigint;
    itemName: string;
    category: PriceCategory;
    washFoldPrice?: number;
}): {
    id: string;
    ironingPrice: [] | [number];
    unit: _PriceUnit;
    steamIroningPrice: [] | [number];
    dryCleaningPrice: [] | [number];
    updatedAt: bigint;
    itemName: string;
    category: _PriceCategory;
    washFoldPrice: [] | [number];
} {
    return {
        id: value.id,
        ironingPrice: value.ironingPrice ? candid_some(value.ironingPrice) : candid_none(),
        unit: to_candid_PriceUnit_n5(_uploadFile, _downloadFile, value.unit),
        steamIroningPrice: value.steamIroningPrice ? candid_some(value.steamIroningPrice) : candid_none(),
        dryCleaningPrice: value.dryCleaningPrice ? candid_some(value.dryCleaningPrice) : candid_none(),
        updatedAt: value.updatedAt,
        itemName: value.itemName,
        category: to_candid_PriceCategory_n7(_uploadFile, _downloadFile, value.category),
        washFoldPrice: value.washFoldPrice ? candid_some(value.washFoldPrice) : candid_none()
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    washFold: null;
} | {
    shoeCleaning: null;
} | {
    dryCleaning: null;
} | {
    washSteamIron: null;
} | {
    steamIron: null;
} {
    return value == ServiceType.washFold ? {
        washFold: null
    } : value == ServiceType.shoeCleaning ? {
        shoeCleaning: null
    } : value == ServiceType.dryCleaning ? {
        dryCleaning: null
    } : value == ServiceType.washSteamIron ? {
        washSteamIron: null
    } : value == ServiceType.steamIron ? {
        steamIron: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PickupStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    pickupDone: null;
} | {
    dropDone: null;
} {
    return value == PickupStatus.cancelled ? {
        cancelled: null
    } : value == PickupStatus.pending ? {
        pending: null
    } : value == PickupStatus.pickupDone ? {
        pickupDone: null
    } : value == PickupStatus.dropDone ? {
        dropDone: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceUnit): {
    perPiece: null;
} | {
    perSeat: null;
} | {
    perMeter: null;
} | {
    perKg: null;
} {
    return value == PriceUnit.perPiece ? {
        perPiece: null
    } : value == PriceUnit.perSeat ? {
        perSeat: null
    } : value == PriceUnit.perMeter ? {
        perMeter: null
    } : value == PriceUnit.perKg ? {
        perKg: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceCategory): {
    men: null;
} | {
    bulk: null;
} | {
    kids: null;
} | {
    shoes: null;
} | {
    women: null;
} | {
    household: null;
} {
    return value == PriceCategory.men ? {
        men: null
    } : value == PriceCategory.bulk ? {
        bulk: null
    } : value == PriceCategory.kids ? {
        kids: null
    } : value == PriceCategory.shoes ? {
        shoes: null
    } : value == PriceCategory.women ? {
        women: null
    } : value == PriceCategory.household ? {
        household: null
    } : value;
}
function to_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ServiceType>): Array<_ServiceType> {
    return value.map((x)=>to_candid_ServiceType_n14(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
